### ISSUE TITLE
Bining of ASC speed into sigma increase maximums

### ISSUE THREAD

**Issue by willaguiar** [willaguiar/ASC_and_heat_transport#39]
I have been using xhistogram to bin the ASC speed along the 1 km isobath into density levels  according to [this notebook](https://github.com/COSIMA/cosima-recipes/blob/main/DocumentedExamples/Binning_transformation_from_depth_to_potential_density.ipynb). However, I noticed that after rebbinning the maximums and minimums (along vertical) of the speed increase.: 
<img width="734" alt="Screenshot 2024-05-20 at 2 42 09 PM" src="https://github.com/willaguiar/ASC_and_heat_transport/assets/70033934/08fd70b9-c8a0-44ea-aa82-b7c8fc9fad6c">
<img width="780" alt="Screenshot 2024-05-20 at 2 42 00 PM" src="https://github.com/willaguiar/ASC_and_heat_transport/assets/70033934/a53a7f24-2ec7-4b33-89fb-501ec2b4f9bc">

Since we want the average for the rebining, I calculated the new ASC speed as `xhist(weight=speed*Area)/xhist(Area)`, as suggested by [Xhistogram](https://xhistogram.readthedocs.io/en/latest/tutorial.html) . I tried using volume instead of Area for weighting, and the same intensification happens...... It seems weird to me, as I think we could have different means in the ASC speed between $\sigma$ and $z$ (for non-weighted averages), but the maximums should be the same... Unless I am missing something......

Any ideas @adele-morrison ?

**Comment by adele-morrison** [comment]
Agreed, that doesn't seem right. I think you want to weight by dz. Which grid is u_along on again?

What about testing the different density binning algorithms in that notebook just for a single daily average? Might help to spot where the bug in the xhistogram method is.

**Comment by willaguiar** [comment]
U_along is on the U and V grids. I did a second test using `area*dzt` as weight for the averages, and it gives similar results. Lemme try to weight with only dzt, and other methods to see how it'll look like.

**Comment by willaguiar** [comment]
I tested xhistogram-binning the monthly data with monthly dzt instead. The issue persists. One problem could be that these binning tests Im doing are using the monthly data, instead of daily. 

I couldn't find dzt for IAF_cycle_3.... could we get it by calculating `uhrho/(u*rho) `?

**Comment by willaguiar** [comment]
I believe I figured out why the maximums and minimums of ASC speed are larger in $\sigma$ than in $z$.

Explanation: 
Umin(z) has to always be more negative than Umin(sigma), since Usigma is binned and averaged from Uz.  That indeed happens monthly( see that delta Umin (z – sigma) is always negative in the hovmoller below, as it should) 
<img width="720" alt="Screenshot 2024-05-24 at 11 16 56 AM" src="https://github.com/willaguiar/ASC_and_heat_transport/assets/70033934/569fff04-0320-4794-9ca4-338bd20155d5">
The delta is only positive when we average between months in each year ( hovmoller below for annual means, black line 7E, green line 225W)
<img width="725" alt="Screenshot 2024-05-24 at 11 18 21 AM" src="https://github.com/willaguiar/ASC_and_heat_transport/assets/70033934/fc4c1349-7b1d-44a8-8eb8-3621c912d3df">
That is because at the sigma resolution chosen, we end up not having ASC speed in all sigma layers during the whole year, and therefore the minimum(sigma) don’t get properly averaged by the nanmean. While in Z levels, the minimum gets averaged. Check for example the case 7E below, year 2000, where the minimum occurs in May, at surface and around 1027.4…
<img width="320" alt="Screenshot 2024-05-24 at 11 24 24 AM" src="https://github.com/willaguiar/ASC_and_heat_transport/assets/70033934/7210a13b-bf5b-4799-9e3b-f3ccad04d0de"><img width="350" alt="Screenshot 2024-05-24 at 11 42 39 AM" src="https://github.com/willaguiar/ASC_and_heat_transport/assets/70033934/037b057d-0020-411b-8c2b-1c4aa2d53c2c">
For comparisson, look below at the 225W case , where Umin(z) is always more negative than Umin(sigma) both monthly and annually (e.g., two first plots of this issue). In this case the Umin at ~1027.5 seem to be more reasonably averaged with speeds in July and December
<img width="350" alt="Screenshot 2024-05-24 at 11 38 15 AM" src="https://github.com/willaguiar/ASC_and_heat_transport/assets/70033934/c4b3c966-9d05-4e0c-8ad6-6eb628cf2201"><img width="400" alt="Screenshot 2024-05-24 at 11 39 50 AM" src="https://github.com/willaguiar/ASC_and_heat_transport/assets/70033934/db4ed1e0-4971-4ed7-8ec4-aa0ba92ddd83">
Bottomline, the problem is likely because of the high-resolution bin spacing. This should be solved once we have the data separated into 3-6 large sigma bins as discussed in the last meeting.

I think for the next steps we should move on to decide which density bins classification we will use, and afterwards revisit this ASC speed issue to see if the problem went away.
